Repository sherlock-project/sherlock, pull requests merged in 2019-07, with the labels that each got.

#233 Update claimed username for BitBucket.
  data.json
Labels: bug

#234 Travis CI: Add more flake8 tests
  .travis.yml
Labels: enhancement

#248 Robustness Update For CI Tests (Part 1)
  .travis.yml
  tests/all.py
Labels: enhancement

#249 Travis CI: Add SherlockSiteCoverageTests as a parallel run
  .travis.yml
Labels: enhancement

#254 Fix Error When csv Is Written When Username Is Illegal For A Site
  sherlock.py
Labels: bug

#226 Don't show invalid/error social site if --print-found flag is enabled.
  sherlock.py
Labels: feature

#263 Fix MixCloud false positive.
  data.json
Labels: bug
