Repository sherlock-project/sherlock, pull requests merged in 2019-01, with the labels that each got.

#72 Script for installing packages in linux
  install_packages.sh
Labels: enhancement, help wanted

#83 Use Colorama syntax for better readability.
  sherlock.py
Labels: enhancement

#101 Command Line Option To Specify Sub-Set Of Sites To Query
  README.md
  sherlock.py
Labels: enhancement

#96 Fixed #95
  sherlock.py
Labels: bug

#109 Response time metrics
  README.md
  sherlock.py
Labels: enhancement
