Repository sherlock-project/sherlock, pull requests merged in 2020-05, with the labels that each got.

#590 Sherlock Restructure (Take 2)
  README.md
  data_bad_site.json
  load_proxies.py
  removed_sites.md
  sherlock/__init__.py
  sherlock/__main__.py
  sherlock/notify.py
  sherlock/resources/data.json
  sherlock/result.py
  sherlock/sherlock.py
  sherlock/sites.py
  sherlock/tests/__init__.py
  sherlock/tests/all.py
  sherlock/tests/base.py
  site_list.py
Labels: enhancement

#599 Support HTTP Status Detection GET Override. Use For Instagram
  README.md
  sherlock/resources/data.json
  sherlock/sherlock.py
Labels: bug, enhancement

#600 Add change directory to CI so tests are executed in proper context.
  .travis.yml
  README.md
Labels: bug

#607 Set python version based on file change
  .github/workflows/sherlock_test.yml
Labels: enhancement

#622 Clean out unused imports
  sherlock/sherlock.py
  sherlock/sites.py
  sherlock/tests/base.py
Labels: enhancement

#623 Use `is` operator when comparing singletons.
  sherlock/notify.py
  sherlock/sherlock.py
  sherlock/sites.py
Labels: enhancement
