Repository sherlock-project/sherlock, pull requests merged in 2020-11, with the labels that each got.

#839 Fixed many of the false positives
  removed_sites.json
  removed_sites.md
  sherlock/resources/data.json
Labels: false negative

#836 Change if statement in __main__.py
  sherlock/__main__.py
Labels: enhancement

#838 Add support for Apple Discussions
  sherlock/resources/data.json
Labels: site support request

#792 Added support for ICQ
  sherlock/resources/data.json
Labels: site support request

#851 Add 500px check
  removed_sites.json
  removed_sites.md
  sherlock/resources/data.json
  sherlock/tests/all.py
Labels: site support request

#850 added Quizlet and Atom Discussions
  sherlock/resources/data.json
  sites.md
Labels: site support request

#862 Consistent comment style
  sherlock/result.py
  sherlock/sherlock.py
  sherlock/sites.py
Labels: enhancement

#868 Add support for GitHub Support Communities
  sherlock/resources/data.json
Labels: site support request

#872 Add support for TETR.IO
  sherlock/resources/data.json
  sites.md
Labels: site support request
