Repository sherlock-project/sherlock, pull requests merged in 2024-11, with the labels that each got.

#2267 Deprecate Python 3.8
  .github/workflows/regression.yml
  pyproject.toml
  sherlock_project/__main__.py
  tests/sherlock_interactives.py
  tox.ini
Labels: bug

#2356 Overload `--json` to fetch via PR number
  sherlock_project/sherlock.py
Labels: enhancement

#2339 fix: add additional error message check for archive.org downtime
  sherlock_project/resources/data.json
Labels: false positive

#2277 Comply with PEP 561
  sherlock_project/py.typed
  sherlock_project/sherlock.py
Labels: enhancement

#2287 fix #2242
  sherlock_project/resources/data.json
Labels: bug, false negative
