Repository sherlock-project/sherlock, pull requests merged in 2024-06, with the labels that each got.

#2150 Update EyeEm test method
  sherlock/resources/data.json
Labels: false positive

#2154 Revamp issue forms
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/false-negative.yml
  .github/ISSUE_TEMPLATE/false-positive.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/site-request.yml
Labels: enhancement

#2127 Switch to Poetry, adopt tox and pytest
  .github/CODEOWNERS
  .github/FUNDING.yml
  .github/workflows/main.yml
  .github/workflows/nightly.yml
  .github/workflows/pull_request.yml
  .github/workflows/regression.yml
  .gitignore
  docs/CONTRIBUTING.md
  docs/INSTALL.md
  docs/README.md
  docs/pyproj/README.md
  pyproject.toml
  pytest.ini
  requirements.txt
  setup.cfg
  setup.py
  sherlock-project.spec
  sherlock/__init__.py
  sherlock/__main__.py
  sherlock/notify.py
  sherlock/sherlock.py
  sherlock/sites.py
  sherlock/tests/__init__.py
  sherlock/tests/all.py
  sherlock/tests/base.py
  sherlock/tests/test_multiple_usernames.py
  tests/conftest.py
  tests/few_test_basic.py
  tests/sherlock_interactives.py
  tests/test_manifest.py
  tests/test_probes.py
  tests/test_ux.py
  tests/test_version.py
  tox.ini
Labels: enhancement

#2159 [2152-fix] fixed issue #2152
  sherlock/resources/data.json
Labels: false positive

#2160 Update install docs
  docs/INSTALL.md
  docs/README.md
Labels: enhancement

#2175 Fix CODEOWNER transposition error
  .github/CODEOWNERS
Labels: bug

#2189 Fix CI Linting
  .github/workflows/regression.yml
Labels: bug
