Repository sherlock-project/sherlock, pull requests merged in 2025-10, with the labels that each got.

#2558 feat: Add some popular website in Korea
  sherlock_project/resources/data.json
Labels: hacktoberfest-accepted

#2597 Support multiple errorType checks
  sherlock_project/resources/data.schema.json
  sherlock_project/sherlock.py
Labels: enhancement

#2200 removed support for tor
  pyproject.toml
  sherlock_project/sherlock.py
Labels: staged - do not merge

#2595 Add Docker build test to CI workflow (#2196)
  .github/workflows/regression.yml
  Dockerfile
Labels: enhancement
